title: Xin Lei Lin
email: xinlei55555@gmail.com
name: "Xin Lei Lin"
description: >-
  Home Page
baseurl: ""
url: "https://xinlei55555.github.io"
github_username: xinlei55555

# Theme and plugins
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom layout
layouts: "default"
permalink: pretty